version: '3'
services:
  db:
    image: mysql
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: persons
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_NAME: mysql
